# Project information
site_name: VS IMPOSTOR Zside Wiki  # サイト名
site_url: http://youbadao.github.io/VS_IMPOSTOR_Zside_Wiki  # サイトのURL
site_description: The VS IMPOSTOR Zside Wiki  # サイトの説明
site_author: Youbadao  # サイトの作成者
repo_url: https://github.com/youbadao-sussy/VS_IMPOSTOR_Zside_Wiki  # リポジトリのURL
repo_name: youbadao-sussy/VS_IMPOSTOR_Zside_Wiki  # リポジトリ名

# Copyright
copyright: 'Copyright © 2026 Youbadao. All rights reserved.'  # 著作権情報

theme:
  name: 'material'  # テーマの名前
  language: 'ja'
  palette:
    primary: yellow
  logo: img/appicon.svg
  favicon: img/icon.svg
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search:
      lang:
        - ja
        - en
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: ja
          name: 日本語
          build: true
          default: true
        - locale: en
          name: English
          build: true
          default: false
      reconfigure_material: true
      reconfigure_search: true
      nav_translations:
        en:
          site_name: VS IMPOSTOR Zside Wiki
          ホーム: Home
          テスト: Test
          全バージョン及び今後のアップデート: All Version & Upcoming Update
          v1.x 系列: v1.x
          キャラクター紹介: Character Information
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Tokyo
      locale: ja
      fallback_to_build_date: true

extra:
  alternate:
    - name: 日本語
      link: /VS_IMPOSTOR_Zside_Wiki/
      lang: ja
    - name: English
      link: /VS_IMPOSTOR_Zside_Wiki/en/
      lang: en

# 拡張機能の設定
markdown_extensions:
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  - footnotes
#  - def_list
#  - pymdownx.tasklist:
#    custom_checkbox: true
#  - attr_list
#  - md_in_html

  - mdx_truly_sane_lists:
      nested_indent: 2

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

nav:
  - ホーム: index.md
  - テスト: test.md
  - 全バージョン及び今後のアップデート:
    - v1.x 系列:
        1.0.0 - The Skeld Update: version/v1_0.md
        1.1.0 - The Meltdown Update (Pitstop / Upcoming): version/v1_1.md
  - キャラクター紹介:
      Boyfriend (Zside): chars/boyfriend-zside.md
