# Project information
site_name: VS IMPOSTOR Zside Wiki  # サイト名
site_url: http://youbadao.github.io/VS_IMPOSTOR_Zside_Wiki  # サイトのURL
site_description: The VS IMPOSTOR Zside Wiki  # サイトの説明
site_author: Youbadao  # サイトの作成者
repo_url: https://github.com/youbadao-sussy/VS_IMPOSTOR_Zside_Wiki  # リポジトリのURL
repo_name: youbadao-sussy/VS_IMPOSTOR_Zside_Wiki  # リポジトリ名

# Copyright
copyright: 'Copyright © 2026 Youbadao. All rights reserved.'  # 著作権情報

theme:
  name: 'material'  # テーマの名前
  palette:
    primary: yellow
  logo: img/appicon.svg
  favicon: img/icon.svg
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home: index.md
  - Test: test.md
  - All Version:
    - v1.x 系列:
        1.0.0 - The Skeld Update: version/v1_0.md
        1.1.0 - The Meltdown Update (Pitstop / Upcoming): version/v1_1.md
  - Characters:
      Boyfriend (Zside): chars/boyfriend-zside.md

# 拡張機能の設定
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  - footnotes
#  - codehilite
#  - def_list
#  - pymdownx.tasklist:
#    custom_checkbox: true
#  - attr_list
#  - md_in_html

  - mdx_truly_sane_lists:
      nested_indent: 2

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
