name: Deploy MkDocs to GitHub Pages
on:
    push:
        branches: main
        paths: 
            - mkdocs.yml
            - mkdocs/**

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages
          
      - run: pip install -r requirements.txt
      - name: Deploy HTML files
        run: python3 -m mkdocs gh-deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
